Subject.create(name: "Accounting and Information Systems")
Subject.create(name: "Actuarial Science")
Subject.create(name: "African Cultural Studies")
Subject.create(name: "Afro-American Studies")
Subject.create(name: "Agricultural and Applied Economics")
Subject.create(name: "Agroecology")
Subject.create(name: "Agronomy")
Subject.create(name: "Air Force Aerospace Studies")
Subject.create(name: "American Indian Studies")
Subject.create(name: "Anatomy")
Subject.create(name: "Anatomy & Physiology")
Subject.create(name: "Anesthesiology")
Subject.create(name: "Animal Sciences")
Subject.create(name: "Anthropology")
Subject.create(name: "Applied Biotechnology")
Subject.create(name: "Art Department")
Subject.create(name: "Art Education")
Subject.create(name: "Art History")
Subject.create(name: "Asian American Studies")
Subject.create(name: "Asian Languages and Cultures")
Subject.create(name: "Asian Languages and Cultures: Languages")
Subject.create(name: "Astronomy")
Subject.create(name: "Atmospheric and Oceanic Sciences")
Subject.create(name: "Biochemistry")
Subject.create(name: "Biological Systems Engineering")
Subject.create(name: "Biology")
Subject.create(name: "Biology Core Curriculum")
Subject.create(name: "Biomedical Engineering")
Subject.create(name: "Biomolecular Chemistry")
Subject.create(name: "Biostatistics and Medical Informatics")
Subject.create(name: "Botany")
Subject.create(name: "Cell and Regenerative Biology")
Subject.create(name: "Chemical and Biological Engineering")
Subject.create(name: "Chemistry")
Subject.create(name: "Chicana/o and Latina/o Studies")
Subject.create(name: "Civil and Environmental Engineering")
Subject.create(name: "Civil Society and Community Studies")
Subject.create(name: "Classics")
Subject.create(name: "Collaborative Nursing Program")
Subject.create(name: "Communication Arts")
Subject.create(name: "Communication Sciences and Disorders")
Subject.create(name: "Community and Environmental Sociology")
Subject.create(name: "Comparative Biosciences")
Subject.create(name: "Comparative Literature")
Subject.create(name: "Computer Sciences")
Subject.create(name: "Consumer Science")
Subject.create(name: "Counseling Psychology")
Subject.create(name: "Curriculum and Instruction")
Subject.create(name: "Dairy Science")
Subject.create(name: "Dance")
Subject.create(name: "Dermatology")
Subject.create(name: "Design Studies")
Subject.create(name: "East Asian Area Studies")
Subject.create(name: "Economics")
Subject.create(name: "Educational Leadership and Policy Analysis")
Subject.create(name: "Educational Psychology")
Subject.create(name: "Education Policy Studies")
Subject.create(name: "Electrical and Computer Engineering")
Subject.create(name: "Emergency Medicine")
Subject.create(name: "Engineering Mechanics and Astronautics")
Subject.create(name: "Engineering Physics")
Subject.create(name: "Engineering Professional Development")
Subject.create(name: "English as a Second Language")
Subject.create(name: "English")
Subject.create(name: "Entomology")
Subject.create(name: "Environmental Studies")
Subject.create(name: "Family Medicine")
Subject.create(name: "Farm and Industry Short Course")
Subject.create(name: "Finance, Investment and Banking")
Subject.create(name: "Folklore Program")
Subject.create(name: "Food Science")
Subject.create(name: "Forest and Wildlife Ecology")
Subject.create(name: "French")
Subject.create(name: "Gender and Womens Studies")
Subject.create(name: "General Business")
Subject.create(name: "Genetics")
Subject.create(name: "Geography")
Subject.create(name: "Geological Engineering")
Subject.create(name: "Geoscience")
Subject.create(name: "German")
Subject.create(name: "German, Nordic, and Slavic")
Subject.create(name: "Greek")
Subject.create(name: "Hebrew-Biblical")
Subject.create(name: "Hebrew-Modern")
Subject.create(name: "History")
Subject.create(name: "History of Science")
Subject.create(name: "Horticulture")
Subject.create(name: "Human Development and Family Studies")
Subject.create(name: "Human Oncology")
Subject.create(name: "Industrial and Systems Engineering")
Subject.create(name: "Information Systems")
Subject.create(name: "Integrated Arts")
Subject.create(name: "Integrated Liberal Studies")
Subject.create(name: "Integrated Science")
Subject.create(name: "Interdisciplinary Courses")
Subject.create(name: "International Business")
Subject.create(name: "International Studies")
Subject.create(name: "Italian")
Subject.create(name: "Jewish Studies")
Subject.create(name: "Journalism and Mass Communication")
Subject.create(name: "Kinesiology")
Subject.create(name: "Landscape Architecture")
Subject.create(name: "Latin American, Caribbean, and Iberian Studies")
Subject.create(name: "Latin")
Subject.create(name: "Law")
Subject.create(name: "Legal Studies")
Subject.create(name: "Library and Information Studies")
Subject.create(name: "Life Sciences Communication")
Subject.create(name: "Linguistics")
Subject.create(name: "Literature in Translation")
Subject.create(name: "Management and Human Resources")
Subject.create(name: "Marketing")
Subject.create(name: "Materials Science and Engineering")
Subject.create(name: "Mathematics")
Subject.create(name: "Mechanical Engineering")
Subject.create(name: "Medical Genetics")
Subject.create(name: "Medical History and Bioethics")
Subject.create(name: "Medical Microbiology and Immunology")
Subject.create(name: "Medical Physics")
Subject.create(name: "Medical Sciences")
Subject.create(name: "Medicine")
Subject.create(name: "Medieval Studies")
Subject.create(name: "Microbiology")
Subject.create(name: "Military Science")
Subject.create(name: "Molecular and Environmental Toxicology Center")
Subject.create(name: "Molecular Biology")
Subject.create(name: "Music")
Subject.create(name: "Music-Performance")
Subject.create(name: "Naval Science")
Subject.create(name: "Neurological Surgery")
Subject.create(name: "Neurology")
Subject.create(name: "Neuroscience")
Subject.create(name: "Neuroscience Training Program")
Subject.create(name: "Nuclear Engineering")
Subject.create(name: "Nursing")
Subject.create(name: "Nutritional Sciences")
Subject.create(name: "Obstetrics and Gynecology")
Subject.create(name: "Occupational Therapy")
Subject.create(name: "Oncology")
Subject.create(name: "Operations and Technology Management")
Subject.create(name: "Ophthalmology and Visual Sciences")
Subject.create(name: "Patho-Biological Sciences")
Subject.create(name: "Pathology and Laboratory Medicine")
Subject.create(name: "Pediatrics")
Subject.create(name: "Pharmaceutical Sciences")
Subject.create(name: "Pharmacology")
Subject.create(name: "Pharmacy")
Subject.create(name: "Pharmacy Practice")
Subject.create(name: "Philosophy")
Subject.create(name: "Physical Therapy")
Subject.create(name: "Physician Assistant Program")
Subject.create(name: "Physics")
Subject.create(name: "Physiology")
Subject.create(name: "Plant Pathology")
Subject.create(name: "Political Science")
Subject.create(name: "Population Health Sciences")
Subject.create(name: "Portuguese")
Subject.create(name: "Psychiatry")
Subject.create(name: "Psychology")
Subject.create(name: "Public Health")
Subject.create(name: "Radiology")
Subject.create(name: "Real Estate and Urban Land Economics")
Subject.create(name: "Rehabilitation Medicine")
Subject.create(name: "Rehabilitation Psychology and Special Education")
Subject.create(name: "Religious Studies")
Subject.create(name: "Risk Management and Insurance")
Subject.create(name: "Scandinavian Studies")
Subject.create(name: "Science and Technology Studies")
Subject.create(name: "Slavic")
Subject.create(name: "Social and Administrative Pharmacy")
Subject.create(name: "Social Work")
Subject.create(name: "Sociology")
Subject.create(name: "Soil Science")
Subject.create(name: "Spanish")
Subject.create(name: "Statistics")
Subject.create(name: "Surgery")
Subject.create(name: "Surgical Sciences")
Subject.create(name: "Theatre and Drama")
Subject.create(name: "Urban and Regional Planning")
Subject.create(name: "Zoology")